version: '3.9'

services:
  db:
    image: mongo:latest
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./pgdata:/var/lib/postgresql/data

  # api:
  #   container_name: api
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: ./DockerfileDev
  #   ports:
  #     - 3001:3001
  #   env_file: .env
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=${DB_PORT}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_DATABASE=${DB_DATABASE}
  #   volumes:
  #     - ./src:/usr/app/src
  #     - ./node_modules
  #   networks:
  #     - postgres
  #   restart: unless-stopped

networks:
  postgres:
    driver: bridge
